version: "3.8"  
services:

  musicapp:
    build: ./musicapp
    volumes:
      - ./musicapp:/app
      - /app/node_modules
    ports:
      - "80:4200"

  songdatabase:
    image: "mongo"

  songapi:
    build: ./songservice/songapi
    volumes:
      - ./songservice/songapi:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment: 
      - PORT=8080
